### ISSUE TITLE
org.freedesktop.Platform.GL.default/x86_64/22.08

### ISSUE THREAD

**Issue by darioandreella** [Elleo/pied#19] opened 2024-09-27 05:05 UTC
Hi, love the project, one of the few ways I found so far to have TTS working, until it broke...

Pied (flatpak) stopped working after org.freedesktop.Platform.GL.default/x86_64 was updated.

I tried to uninstall it and re-install it (it doesn't seem to be found with Discover on flatpak repo, I downloaded it manually), and now it won't even install, because "org.freedesktop.Platform.GL.default/x86_64/22.08 is not installed" (it is, but on the latest version!).

Arch Linux on 6.6.10, Plasma 6.1.5 (wayland).

Thanks, hope we can have it back!

Dario

**Comment by Elleo** [comment] 2024-09-28 21:44
Hi @darioandreella 

This looks like a duplicate of #18, could you give the new upload a test and see if that fixes your issue? (It's now built against 24.08)

Thanks,
Mike

**Comment by archisman-panigrahi** [comment] 2024-11-14 15:33
I tested that it works. Can you please release a new (minor) version, and optionally, publish to flathub?

**Comment by Elleo** [comment] 2024-11-16 20:50
Great, thanks! I'll be putting out a new release shortly :)

**Closed by Elleo** 2024-11-16 20:50 UTC
